[package]
name = "rosalind"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "dna"
path = "src/dna.rs"

[[bin]]
name = "rna"
path = "src/rna.rs"

[[bin]]
name = "revc"
path = "src/revc.rs"

[[bin]]
name = "fib"
path = "src/fib.rs"